### ISSUE TITLE
[Prediction] Negative numbers on large date ranges

### ISSUE THREAD

**Issue by SeoboS** [ZacBlanco/ChefBoyRD#24]
![selection_022](https://cloud.githubusercontent.com/assets/7828315/24442453/3a2ee696-142c-11e7-8036-5ebaa5686d9c.png)

![selection_027](https://cloud.githubusercontent.com/assets/7828315/24442591/cdd80706-142c-11e7-9e78-cabed0a87903.png)

Large negative numbers sometimes shown for the value, when using prediction feature. Seems to occur for random items with large date ranges.

**Comment by ZacBlanco** [comment]
@richardahn and I discussed this. It has to do with not having enough training data for certain ranges of dates.

We'll need to restrict the values allowed in order to make accurate predictions

**Comment by ZacBlanco** [comment]
@richardahn can you confirm we've fixed this entire issue

**Comment by ZacBlanco** [comment]
Fixed - closing
